version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://benome_user:${DB_PASSWORD}@db:5432/benomedb
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=500d
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=benome_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=benomedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
