# Fichier de configuration pour le déploiement sur Render
# Documentation : https://render.com/docs/deploy-web-services

services:
  - type: web
    name: officielbenome-backend
    env: node
    region: oregon
    plan: free
    buildCommand: chmod +x start.sh && npm install --legacy-peer-deps && npm run build
    startCommand: ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: benomedb
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 500d
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.com
    healthCheckPath: /api/health
    autoDeploy: true
    numInstances: 1

databases:
  - name: benomedb
    databaseName: benomedb
    user: benome_user
    plan: free
