# Fichier de configuration pour le déploiement sur Render
# Documentation : https://render.com/docs/deploy-web-services

services:
  - type: web
    name: officielbenome-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: benomedb
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 500d
      - key: JWT_COOKIE_EXPIRES_IN
        value: "90"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://benome4u.vercel.app
      - key: REDIS_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    numInstances: 1

databases:
  - name: benomedb
    databaseName: benomedb
    user: benome_user
    plan: free
